
 USE [master]

GO
/****** Object:  Database [QUANLYNHAHANG]    ******/
CREATE DATABASE [QUANLYNHAHANG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QUANLYNHAHANG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QUANLYNHAHANG.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QUANLYNHAHANG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QUANLYNHAHANG_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [QUANLYNHAHANG] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QUANLYNHAHANG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QUANLYNHAHANG] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET ARITHABORT OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QUANLYNHAHANG] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QUANLYNHAHANG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QUANLYNHAHANG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QUANLYNHAHANG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QUANLYNHAHANG] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QUANLYNHAHANG] SET  MULTI_USER 
GO
ALTER DATABASE [QUANLYNHAHANG] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QUANLYNHAHANG] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QUANLYNHAHANG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QUANLYNHAHANG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QUANLYNHAHANG] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QUANLYNHAHANG] SET QUERY_STORE = OFF
GO
USE [QUANLYNHAHANG]
GO
/****** Object:  Table [dbo].[BANAN]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANAN](
	[MABAN] [char](10) NOT NULL,
	[SOCHONGOI] [int] NOT NULL,
	[MAPYC] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[MABAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHITIETDATMON]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETDATMON](
	[MAPYC] [char](10) NOT NULL,
	[MAMA] [char](10) NOT NULL,
	[DONGIA] [int] NOT NULL,
	[SOLUONG] [int] NOT NULL,
	[THANHTIEN] [int] NOT NULL,
 CONSTRAINT [MONAN_PHIEUYEUCAU] PRIMARY KEY CLUSTERED 
(
	[MAPYC] ASC,
	[MAMA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHITIETPHIEUNHAP]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETPHIEUNHAP](
	[MAPN] [char](10) NOT NULL,
	[MANL] [char](10) NOT NULL,
	[DONGIA] [int] NOT NULL,
	[SOLUONG] [int] NOT NULL,
	[THANHTIEN] [int] NOT NULL,
 CONSTRAINT [NGUYENLIEU_PHIEUNHAP] PRIMARY KEY CLUSTERED 
(
	[MANL] ASC,
	[MAPN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[MAHD] [char](10) NOT NULL,
	[NGAYLAP] [datetime] NULL,
	[TONGTIEN] [int] NULL,
	[USERNAME] [varchar](30) NULL,
	[MAPYC] [char](10) NOT NULL,
	[MAKM] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MAKH] [char](10) NOT NULL,
	[TENKH] [nvarchar](50) NOT NULL,
	[SDT] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHUYENMAI]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHUYENMAI](
	[MAKM] [char](10) NOT NULL,
	[NGAYBATDAU] [date] NOT NULL,
	[NGAYKETTHUC] [date] NOT NULL,
	[PHANTRAM] [decimal](18, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAKM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAIMON]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAIMON](
	[MALOAI] [char](10) NOT NULL,
	[TENLOAIMON] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MALOAI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MONAN]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
//THEM BANG MONAN
CREATE TABLE [dbo].[MONAN](
	[MAMA] [char](10) NOT NULL,
	[TENMONAN] [nvarchar](100) NOT NULL,
	[DVT] [nvarchar](20) NOT NULL,
	[DONGIA] [int] NOT NULL,
	[MALOAI] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAMA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NGUYENLIEU]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NGUYENLIEU](
	[MANL] [char](10) NOT NULL,
	[TENNL] [nvarchar](50) NOT NULL,
	[DVT] [nvarchar](30) NOT NULL,
	[DONGIA] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MANL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHACUNGCAP]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHACUNGCAP](
	[MANCC] [char](10) NOT NULL,
	[TENNCC] [nvarchar](50) NOT NULL,
	[DIACHI] [nvarchar](100) NOT NULL,
	[SDT] [char](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MANCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [char](10) NOT NULL,
	[TENNV] [nvarchar](50) NOT NULL,
	[NGAYSINH] [date] NOT NULL,
	[DIACHI] [nvarchar](100) NOT NULL,
	[GIOITINH] [nchar](3) NOT NULL,
	[SDT] [char](10) NULL,
	[LUONG] [int] NOT NULL,
	[NGAYVAOLAM] [date] NOT NULL,
	[CHUCVU] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUNHAP]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUNHAP](
	[MAPN] [char](10) NOT NULL,
	[NGAYLAP] [datetime] NULL,
	[TONGTIEN] [int] NOT NULL,
	[MANCC] [char](10) NOT NULL,
	[USERNAME] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAPN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUYEUCAU]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUYEUCAU](
	[MAPYC] [char](10) NOT NULL,
	[NGAYLAP] [datetime] NULL,
	[USERNAME] [varchar](30) NULL,
	[MAKH] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAPYC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAIKHOAN]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAIKHOAN](
	[USERNAME] [varchar](30) NOT NULL,
	[PASSWORD] [varchar](1000) NOT NULL,
	[HOTEN] [nvarchar](50) NOT NULL,
	[PHANQUYEN] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[BANAN] ([MABAN], [SOCHONGOI], [MAPYC]) VALUES (N'1         ', 5, NULL)
INSERT [dbo].[BANAN] ([MABAN], [SOCHONGOI], [MAPYC]) VALUES (N'2         ', 5, NULL)
INSERT [dbo].[BANAN] ([MABAN], [SOCHONGOI], [MAPYC]) VALUES (N'3         ', 3, N'0002      ')
INSERT [dbo].[BANAN] ([MABAN], [SOCHONGOI], [MAPYC]) VALUES (N'4         ', 5, NULL)
INSERT [dbo].[BANAN] ([MABAN], [SOCHONGOI], [MAPYC]) VALUES (N'5         ', 3, N'0001      ')
INSERT [dbo].[BANAN] ([MABAN], [SOCHONGOI], [MAPYC]) VALUES (N'6         ', 3, NULL)
INSERT [dbo].[BANAN] ([MABAN], [SOCHONGOI], [MAPYC]) VALUES (N'7         ', 3, NULL)
INSERT [dbo].[BANAN] ([MABAN], [SOCHONGOI], [MAPYC]) VALUES (N'8         ', 4, NULL)
INSERT [dbo].[BANAN] ([MABAN], [SOCHONGOI], [MAPYC]) VALUES (N'9         ', 4, NULL)
GO
INSERT [dbo].[KHACHHANG] ([MAKH], [TENKH], [SDT]) VALUES (N'kh1       ', N'nguyễn thị c', N'0123456789')
INSERT [dbo].[KHACHHANG] ([MAKH], [TENKH], [SDT]) VALUES (N'kh2       ', N'nguyễn thị d', N'0123455559')
GO
INSERT [dbo].[PHIEUYEUCAU] ([MAPYC], [NGAYLAP], [USERNAME], [MAKH]) VALUES (N'0001      ', CAST(N'2021-02-03T00:00:00.000' AS DateTime), N'nv1', N'kh1       ')
INSERT [dbo].[PHIEUYEUCAU] ([MAPYC], [NGAYLAP], [USERNAME], [MAKH]) VALUES (N'0002      ', CAST(N'2021-02-04T00:00:00.000' AS DateTime), N'nv1', N'kh2       ')
GO
INSERT [dbo].[TAIKHOAN] ([USERNAME], [PASSWORD], [HOTEN], [PHANQUYEN]) VALUES (N'NV1', N'123', N'Nguyễn Thị B', N'Quản lý')
GO
ALTER TABLE [dbo].[HOADON] ADD  DEFAULT (getdate()) FOR [NGAYLAP]
GO
ALTER TABLE [dbo].[PHIEUNHAP] ADD  DEFAULT (getdate()) FOR [NGAYLAP]
GO
ALTER TABLE [dbo].[PHIEUYEUCAU] ADD  DEFAULT (getdate()) FOR [NGAYLAP]
GO
ALTER TABLE [dbo].[BANAN]  WITH CHECK ADD FOREIGN KEY([MAPYC])
REFERENCES [dbo].[PHIEUYEUCAU] ([MAPYC])
GO
ALTER TABLE [dbo].[CHITIETDATMON]  WITH CHECK ADD FOREIGN KEY([MAPYC])
REFERENCES [dbo].[PHIEUYEUCAU] ([MAPYC])
GO
ALTER TABLE [dbo].[CHITIETDATMON]  WITH CHECK ADD FOREIGN KEY([MAMA])
REFERENCES [dbo].[MONAN] ([MAMA])
GO
ALTER TABLE [dbo].[CHITIETPHIEUNHAP]  WITH CHECK ADD FOREIGN KEY([MANL])
REFERENCES [dbo].[NGUYENLIEU] ([MANL])
GO
ALTER TABLE [dbo].[CHITIETPHIEUNHAP]  WITH CHECK ADD FOREIGN KEY([MAPN])
REFERENCES [dbo].[PHIEUNHAP] ([MAPN])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MAKM])
REFERENCES [dbo].[KHUYENMAI] ([MAKM])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MAPYC])
REFERENCES [dbo].[PHIEUYEUCAU] ([MAPYC])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([USERNAME])
REFERENCES [dbo].[TAIKHOAN] ([USERNAME])
GO
ALTER TABLE [dbo].[MONAN]  WITH CHECK ADD FOREIGN KEY([MALOAI])
REFERENCES [dbo].[LOAIMON] ([MALOAI])
GO
ALTER TABLE [dbo].[PHIEUNHAP]  WITH CHECK ADD FOREIGN KEY([MANCC])
REFERENCES [dbo].[NHACUNGCAP] ([MANCC])
GO
ALTER TABLE [dbo].[PHIEUNHAP]  WITH CHECK ADD FOREIGN KEY([USERNAME])
REFERENCES [dbo].[TAIKHOAN] ([USERNAME])
GO
ALTER TABLE [dbo].[PHIEUYEUCAU]  WITH CHECK ADD FOREIGN KEY([USERNAME])
REFERENCES [dbo].[TAIKHOAN] ([USERNAME])
GO
ALTER TABLE [dbo].[PHIEUYEUCAU]  WITH CHECK ADD FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD CHECK  (([GIOITINH]=N'NỮ' OR [GIOITINH]='NAM'))
GO
/****** Object:  StoredProcedure [dbo].[GetTableList]    Script Date: 23/03/2021 8:06:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[GetTableList]
as select * from BANAN
GO
USE [master]
GO
ALTER DATABASE [QUANLYNHAHANG] SET  READ_WRITE 
GO
